version: "3"

services:
  influxdb:
    image: influxdb
    ports:
      - 8086:8086
    networks:
      default:
        aliases:
          - influxdb

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    networks:
      default:
        aliases:
          - grafana

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/24
